### ISSUE TITLE
Fomod installs wrong files

### ISSUE THREAD

**Issue by phen0mX** [limo-app/limo#15]
Found a new fomod issue.
[This fomod](https://www.nexusmods.com/newvegas/mods/82042) installs the wrong files when selecting "FNV Ultimate Edition". 
Resulting in the correct "fixy crap ue.esp", but the incorrect "smim_anims.json". 
Which should come from "src\smim_anims_fnv", but instead seems to come from "src\meshes".
Maybe this is related to 'priority="1"'? Should it overwrite the 'priority="0"' file?

<details>
  <summary>ModuleConfig.xml</summary>

  ```xml
<!-- Created with FOMOD Creation Tool 1.7.0.37 [http://www.nexusmods.com/fallout4/mods/6821] --> 
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://qconsulting.ca/fo3/ModConfig5.0.xsd"> 
	<moduleName>skinned mesh improvement mod</moduleName> 
	<installSteps order="Explicit"> 
		<installStep name="Setup"> 
			<optionalFileGroups order="Explicit"> 
				<group name="Plugin Version" type="SelectExactlyOne"> 
					<plugins order="Explicit"> 
						<plugin name="FNV Ultimate Edition"> 
							<description>plugin for fnv ultimate edition</description> 
							<files> 
								<file source="src\fixy crap ue.esp" destination="fixy crap ue.esp" priority="0" /> 
								<folder source="src\smim_anims_fnv" destination="meshes" priority="1" /> 
								<folder source="src\meshes" destination="meshes" priority="0" /> 
								<folder source="src\textures" destination="textures" priority="0" /> 
							</files> 
							<typeDescriptor> 
								<dependencyType> 
									<defaultType name="Optional"/> 
									<patterns> 
										<pattern> 
											<dependencies operator="And"> 
											</dependencies> 
											<type name="CouldBeUsable"/> 
										</pattern> 
									</patterns> 
								</dependencyType> 
							</typeDescriptor> 
						</plugin> 
						<plugin name="Tale of Two Wastelands"> 
							<description>plugin for tale of two wastelands</description> 
							<files> 
								<file source="src\fixy crap ttw.esp" destination="fixy crap ttw.esp" priority="0" /> 
								<folder source="src\smim_anims_ttw" destination="meshes" priority="1" /> 
								<folder source="src\textures" destination="textures" priority="0" /> 
								<folder source="src\meshes" destination="meshes" priority="0" /> 
							</files> 
							<typeDescriptor> 
								<dependencyType> 
									<defaultType name="Optional"/> 
									<patterns> 
										<pattern> 
											<dependencies operator="And"> 
											</dependencies> 
											<type name="CouldBeUsable"/> 
										</pattern> 
									</patterns> 
								</dependencyType> 
							</typeDescriptor> 
						</plugin> 
					</plugins> 
				</group> 
				<group name="Environment Masks" type="SelectAtMostOne"> 
					<plugins order="Explicit"> 
						<plugin name="Real Time Reflections"> 
							<description>enables environment masks with roughness; meant to be used with real time reflections&#13;&#10;
&#13;&#10;
https://www.nexusmods.com/newvegas/mods/82343</description> 
							<conditionFlags> 
								<flag name="Real Time Reflections">On</flag> 
							</conditionFlags> 
							<files> 
								<folder source="optional\env masks - rtr" destination="textures" priority="2" /> 
							</files> 
							<typeDescriptor> 
								<type name="Optional"/> 
							</typeDescriptor> 
						</plugin> 
					</plugins> 
				</group> 
				<group name="Protectron Domes" type="SelectAtMostOne"> 
					<plugins order="Explicit"> 
						<plugin name="Enable Transparency"> 
							<description>enables unused transparency on protectron domes; rendering issue causes disappearing domes when seen through windows (vendortron)</description> 
							<conditionFlags> 
								<flag name="ProtectronDomes">On</flag> 
							</conditionFlags> 
							<files> 
								<folder source="optional\meshes - protectron domes" destination="meshes" priority="2" /> 
							</files> 
							<typeDescriptor> 
								<type name="Optional"/> 
							</typeDescriptor> 
						</plugin> 
					</plugins> 
				</group> 
			</optionalFileGroups> 
		</installStep> 
	</installSteps> 
</config>
  ```
  
</details>

Edit: The [spec](https://fomod-docs.readthedocs.io/en/latest/_static/ModuleConfig.html) says:
> A number describing the relative priority of the file or folder. A higher number indicates the file or folder should be installed after the items with lower numbers. This value does not have to be unique.

That's horrible. Depending on if it overwrites the previous file the meaning inverts.
But the specification does not address this at all. 😱

**Comment by limo-app** [comment]
How file priority should be handled for FOMOD installations is tricky. For one, the spec is unclear. I am currently not quite clear how overwriting directories should be work. Let's say a mod wants to copy two source directories to the same destination directory. Should files from both sources be installed since they might be meant to complement each other? Should the higher priority one/ earlier one be the only one that is to be installed? Most mod authors seem to think that directories are always merged like this, though i have seen exceptions. 

The current implementation in Limo assumes that directories are to be merged. The reason this FOMOD fails is because it merges directories with different priorities, which i don't think i have ever seen. I believe the mod author's assumption that, in this case, the directories are installed in order and then overwrite each other if needed seems reasonable. Probably best to make this the default behavior and hope that this is the consensus among users.

Unfortunately many FOMOD related implementation details come down to knowing consensus, since the spec can be vague.

**Comment by phen0mX** [comment]
I found [this site](https://stepmodifications.org/wiki/Guide:FOMOD/ModuleConfigXML). Which seems to have a more definitive answer to the "priority" question.

**Comment by limo-app** [comment]
The new implementation in [1d7129d](https://github.com/limo-app/limo/commit/1d7129de828007ef589de4f3823f510cfd70ef8b) now works as described in the guide you linked. Directories are always merged with higher priority ones overwriting single files if there is a conflict.
Good find, most people will probably follow guides like those so this should increase compatibility.

**Comment by limo-app** [comment]
The updated behavior for FOMOD installations, as described [here](https://stepmodifications.org/wiki/Guide:FOMOD/ModuleConfigXML), are now live on Flathub as part of 1.0.5. Closing
