### ISSUE TITLE
State VFS as a feature in the readme

### ISSUE THREAD

**Issue by Afurai** [limo-app/limo#18]
I believe stating this as a feature would clear up confusion regarding Limo as a direct MO2 replacement for many potential users.

**Comment by limo-app** [comment]
As it stands right now Limo is missing a feature of MO2's VFS: The overwrite directory. This will be added later in the form of a *Reverse Deployer*, which scans it's target directory and pulls out all files not managed by another deployer and then links them back in.

While i agree that mentioning VFS as a feature will help people familiar with MO2, i will wait with adding it to the list of features until the *Reverse Deployer* has been implemented. In the meantime i've added a section that should help people get an idea of how Limo works in [b4cabcb](https://github.com/limo-app/limo/commit/b4cabcb527d8d6d019d4c05c0db12617dbf8366b).

**Comment by Afurai** [comment]
I understand, thank you. I only mentioned this because others' asked when I tossed them over this way. I will keep track and let others know when the feature is in, so they can completely replace mo2. Again, thank you.
