### ISSUE TITLE
What is the staging directory?

### ISSUE THREAD

**Issue by yochananmarqos** [limo-app/limo#19]
I've imported Oblivion from Steam, however the Staging directory field is required. Why isn't it populated automatically? Why should a user know what it is?

![image](https://github.com/user-attachments/assets/6575d245-a960-4cd7-960e-dcc4ebba2cda)

**Comment by yochananmarqos** [comment]
You lost me there. I already have mods installed manually. LOOT already detects them, why doesn't LIMO?

![image](https://github.com/user-attachments/assets/daa28caf-27a3-442c-8e4e-40a60205ec62)

**Comment by yochananmarqos** [comment]
Update (also see my edit above): I created a mods folder and set `~.steam/steam/steamapps/common/Oblivion/mods/` as the staging directory. That apparently did nothing.

![image](https://github.com/user-attachments/assets/84bd3bbe-5b01-449b-b6ba-e2f2b581da93)

**Comment by phen0mX** [comment]
> EDIT: Oh, I think I know what you're referring to. Limo is meant to be more like mod managers that install mods separately and do dynamic patching. Is that right?

Yes. 

It will not matter what you do to your game folder.
Limo will only ever care about mods (files) installed through it's interface.
Because that's how mod managers work. I don't quite understand how you expect it to work though. It has no idea which files in your game folder are mods and which are regular game files as they are effectively indistinguishable.

**Comment by yochananmarqos** [comment]
> It has no idea which files in your game folder are mods and which are regular game files as they are effectively indistinguishable.

Point taken, makes sense--except all DLCs and some mods use ESP files which LOOT can detect just fine.

Speaking of which, does Limo support load order like LOOT does?

Either way, perhaps Limo needs documentation specifying what it can do, what it can't do and how it compares to LOOT.

**Comment by yochananmarqos** [comment]
> It's the place where the mods get actually installed.

That answers the question, so I suppose this issue can be closed.

**Comment by limo-app** [comment]
[b4cabcb](https://github.com/limo-app/limo/commit/b4cabcb527d8d6d019d4c05c0db12617dbf8366b) added a section in the README that should help with understanding the basics.

**Comment by yochananmarqos** [comment]
Thank you, that's helpful!
