### ISSUE TITLE
File conflicts across multiple deployers not being picked up

### ISSUE THREAD

**Issue by ZetaDaemon** [limo-app/limo#20]
Due to my setup with multiple deployers and mods getting split, it seems that limo is not properly picking up conflicts when you open the "Show file conflicts" menu
![image](https://github.com/user-attachments/assets/67188af1-8c19-4a14-979d-00986978da65)
![image](https://github.com/user-attachments/assets/7f223c8f-4ea7-45a4-8462-9ca5cb6ea110)
as you can see both mods override gd_shields but it says they both are the winner
![image](https://github.com/user-attachments/assets/9dba6782-40b1-4915-a28b-91a1cd071218)
i assume this is because "ZetaPatch" is only in the CookedPC deployer while "Recharge delay on shields" is originally added to my Borderlands deployer but then split into WillowGame and CookedPC

![image](https://github.com/user-attachments/assets/719ae048-2f07-46fc-a6fc-ae27bb67760d)
also the final order i have where ZetaPatch should override everything else

**Comment by phen0mX** [comment]
Could you explain why you have multiple deployers pointed at the same directory?
I don't quite understand how that makes sense.

**Comment by limo-app** [comment]
I checked the code and this bug only affects the file conflicts window. The deployer resolves conflicts as it should. The fix for this will be part of the next update on flathub.

**Comment by ZetaDaemon** [comment]
Yes the load order works fine, its only an issue with the conflicts window

**Comment by ZetaDaemon** [comment]
> Could you explain why you have multiple deployers pointed at the same directory? I don't quite understand how that makes sense.

its because of how bl1 modding works, there is no dedicated mods folder, youre just adding and replacing files throughout the game's directory so different mods need to go into different locations and are shipped differently, so its easier to just make multiple deployers to handle mods needing to go into different locations rather than manually repackaging mods to all work in a single deployer

**Comment by limo-app** [comment]
The file conflicts window has been fixed in 2fb73f7 which is part of 1.0.6.

**Comment by limo-app** [comment]
Closing since this has been fixed in 1.0.6
