### ISSUE TITLE
Flatpack install, Steam Fallout NV works, but doesn't see game expansions like OldWorldBlues - Main.bsa

### ISSUE THREAD

**Issue by sbsaylors** [limo-app/limo#23]
First off this whole thing is amazing. Thank you. The issue I have is I have the Steam Fallout NV install and adding mods are great, but I have the "expansion" files in the data directory but I cant seem to 'use/see' them in Limo. (bsa and esm)

Can I put them 'somewhere' so they show up as mods in Limo?

**Comment by limo-app** [comment]
All the game's esm files should be picked up when you add a *Loot Deployer*, similar to what the [wiki](https://github.com/limo-app/limo/wiki) does. The bsa files can not be distinguished from other game files, and there usually is no need to do so. 
If, for whatever reason, you wish to add them to Limo anyways, i suggest creating a new mod for them:

1. Create a new directory and move all those files into it
2. Drag and drop that directory into Limo and install it as a new mod
3. Add the new mod to the deployer managing the file's original location

Once this all works, you can delete the mod directory you created in step 1.

**Comment by sbsaylors** [comment]
Thanks you Chris! All worked!
