### ISSUE TITLE
Limo Not Receiving Nexus Mods Download Requests

### ISSUE THREAD

**Issue by KrispeeIguana** [limo-app/limo#26]
Dunno what caused this, but it occurred after I closed and reopened the app for a system restart. Logs do not show any mention of Nexus after that even though I've tried manually doing the direct download and regenerating the NMM API key. Reinstalling the Flatpak does not fix the issue.

**Comment by christiandlloyd** [comment]
I also have this issue. Mime is set up to handle nxm links on my end. For me, `xdg-mime query default x-scheme-handler/nxm` outputs `io.github.limo_app.limo.desktop`.

**Comment by Heisenborgar** [comment]
Can confirm. Used to think it's due to my system so I did a full reinstall, still, doesn't work. Downgrading to a lower version doesn't have this issue.

**Comment by limo-app** [comment]
There should be log files written to `~/.var/app/io.github.limo_app.limo/config/Limo/logs/` for the flatpak version, each of which contains all logs for one session. They should contain *[Debug]: Received download request for* when Limo is called by xdg desktop handler for a nxm link. Is this the case for you?

**Comment by christiandlloyd** [comment]
No, all I get is: 
`2024-09-10 19:46:29.83 [Debug]: Running as a flatpak
2024-09-10 19:46:29 [Info]: Startup complete
2024-09-10 19:46:29.305 [Debug]: Debug mode disabled`

**Comment by KrispeeIguana** [comment]
> There should be log files written to `~/.var/app/io.github.limo_app.limo/config/Limo/logs/` for the flatpak version, each of which contains all . . . 

Also no

**Comment by limo-app** [comment]
Are you using a native, Snap or Flatpak browser? I know that flatpak browsers do not follow the rules you get when running `xdg-mime query default`. The file `~/.local/share/flatpak/db/desktop-used-apps` seems to control default apps for flatpaks.

**Comment by KrispeeIguana** [comment]
I unfortunately do not have this file nor do I know how handle it manually

**Comment by KrispeeIguana** [comment]
I'm using Firefox from the Arch Repo

**Comment by KrispeeIguana** [comment]
My problem here might be solved with the mime command. Not sure about @christiandlloyd 's issue tho. Now I gotta deal with the extra default app clutter in the browser.

**Comment by christiandlloyd** [comment]
I'm using native firefox.

**Comment by christiandlloyd** [comment]
Just looked at my default applications for firefox, it was set to "Use Limo" and not "Use Limo (default)." Doing so fixed my error.

**Comment by limo-app** [comment]
> Just looked at my default applications for firefox, it was set to "Use Limo" and not "Use Limo (default)." Doing so fixed my error.

This might be helpful for others.
For people having this issue in the future here are some tips:

If you are using a native browser: Run `xdg-mime query default x-scheme-handler/nxm`, if the output is not `io.github.limo_app.limo.desktop`, Limo is not set as your default application for NXM links.

If you are using a flatpak browser and Limo is not used for NXM links: The file `~/.local/share/flatpak/db/desktop-used-apps` tracks how often a MIME type has been handled by a specific application. If this contains the bytes `33 00 33` after `x-scheme-handler/nxm`, you have previously used another application to handle NXM links. Try replacing those bytes with `30 00 33`. You should now be asked which application to use when downloading from NexusMods.

Since the original issue has been resolved, i will close this issue now.

**Comment by Saigaiii** [comment]
> > Just looked at my default applications for firefox, it was set to "Use Limo" and not "Use Limo (default)." Doing so fixed my error.
> 
> This might be helpful for others. For people having this issue in the future here are some tips:
> 
> If you are using a native browser: Run `xdg-mime query default x-scheme-handler/nxm`, if the output is not `io.github.limo_app.limo.desktop`, Limo is not set as your default application for NXM links.
> 
> If you are using a flatpak browser and Limo is not used for NXM links: The file `~/.local/share/flatpak/db/desktop-used-apps` tracks how often a MIME type has been handled by a specific application. If this contains the bytes `33 00 33` after `x-scheme-handler/nxm`, you have previously used another application to handle NXM links. Try replacing those bytes with `30 00 33`. You should now be asked which application to use when downloading from NexusMods.
> 
> Since the original issue has been resolved, i will close this issue now.

What app did you use to open the desktop-used-apps file? When I try to open it I get wrong characters.
