### ISSUE TITLE
[Not a bug] For someone have issues running Bethini Pie (New Version), do this.

### ISSUE THREAD

**Issue by Heisenborgar** [limo-app/limo#27]
Hi _Depex, this is loki_pat from reddit!

To make Bethini Pie run, execute the following command:
`protontricks --gui`

From there, select your game's prefix, select default prefix, open explorer.exe, then run Bethini.exe from the explorer itself and the tool will run fine.

I will investigate this bug, and I believe it is a wine/proton/protontricks bug

**Comment by limo-app** [comment]
Some applications have to be run in the directory containing the executable. You could try the following command as a tool in Limo:
`--directory="/PATH/TO/DIRECTORY/CONTAINING/BETHINI" protontricks-launch --no-bwrap --appid 489830 Bethini.exe`
Note that the *--no-bwrap* may not be necessary for you, it is for me though.

**Comment by Heisenborgar** [comment]
Not relevant anymore since we now have a guided tool aetup
