### ISSUE TITLE
[Feature Request] Pandora Behaviour Engine support + workaround 

### ISSUE THREAD

**Issue by Heisenborgar** [limo-app/limo#29]
Right now, if you use Pandora Behaviour Engine rather than Nemesis, you'll notice you won't be able to find patches for mods like True Directional Movement. To fix this, you have to install Pandora as a mod, deploy it in Data, copy or cut the files from True Directional Movement's Nemesis_Engine folder, and paste it to Pandora. Run the patcher and the patches should show up.

I think Limo should add like an easy way to do this lmao. Literally took me a week to figure this out

**Comment by limo-app** [comment]
This seems like a really specific issue and i am not sure what the best way to address this would be.
One solution would be to add the option to define a set of directory overrides during installation which allow you to move files from a source directory to another. This would hopefully solve all similar issues.
I will add this to my list, but it might take some time until i get to that.

**Comment by Heisenborgar** [comment]
Closing this issue since I did it wrong. You should not use Pandora's executable from your Mods directory, instead, you have to use Pandora's executable from the Skyrim/Data directory when you deploy it.
