### ISSUE TITLE
[Feature Request] Please Give the Log Files a Github-Compatible Extension

### ISSUE THREAD

**Issue by KrispeeIguana** [limo-app/limo#33]
Unfortunately, files without extensions are incompatible with Github's file upload system. This means if I want to upload say, 11 limo_log-x files, I would need to manually rename each and every one of them to limo_log-x.txt.

**Comment by limo-app** [comment]
Thanks for reporting, i will append *.txt* to all log files for the next update.

**Comment by limo-app** [comment]
Update 1.0.7 added *.txt* to add log files.
Closing
