### ISSUE TITLE
Deloying from Bin CTD

### ISSUE THREAD

**Issue by Nex-Crimen** [limo-app/limo#36]
I have Fallout NV installed on ext4 Drive, I had previously used Mod Organizer 2 to manage it, but it kept crashing. The issue is as mentioned in the title, attempting to Deploy Bin (which only contains xNVSE) fails and crashes, I don't currently know where the logs would be stored. However running it through Terminal gives me the following errors.
`kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "&Yes" msgid_plural: "" msgctxt: "@action:button"`
`kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "&No" msgid_plural: "" msgctxt: "@action:button"`
`/usr/include/c++/13.2.0/bits/stl_vector.h:1125: constexpr std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = ProgressNode; _Alloc = std::allocator<ProgressNode>; reference = ProgressNode&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
`

Now the first two I've seen mentioned elsewhere ([Hard Link Fail](https://github.com/limo-app/limo/issues/13#issuecomment-2310331891)) But wasn't able to find anything regarding the last error. I switched over to Sym Links as Hard Links where not working for me. 

I'm using the flatpak version and am on EndeavourOS.

**Comment by Nex-Crimen** [comment]
Ok, so as a test I attempted to link my Skyrim installation to this. By default Limo can't seem to find my LibraryFolder.vdf, I've found versions of this file, 2 on my home drive, both of which only provide the Steamworks Common Redistributables - I have a separate hard drive where I have my games installed and when I attempt to load the LibraryFolder.vdf from there, it claims there it does not exist. I can see it in my Steam folder (for some reason its before steamapps), but it can't be read.

I imagine that this is linked to the previous issue in some way or another, so hopefully this information helps identify my problem for those that know better than me.

If you require more information to help me diagnose the issue, please let me know.

**Comment by limo-app** [comment]
> attempting to Deploy Bin (which only contains xNVSE) fails and crashes

Could you share a log for created when this crash occurs? They are stored in `/.var/app/io.github.limo_app.limo/config/Limo/logs/` for the flatpak version.

> I have a separate hard drive where I have my games installed and when I attempt to load the LibraryFolder.vdf from there, it claims there it does not exist.

This sounds like an issue with flatpak permissions. Where is this hard drive mounted?
There should be a libraryfolders.vfd file in `~/.steam/steam/steamapps` for native installs or in  `~/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps` for the flatpak version. This file should contain all external library folders used by your Steam installation.

**Comment by Nex-Crimen** [comment]
Here's the log where the crash occurs - showing me attempting to hard link the Bin and then attempting the syslink which crashes everything.
[limo_log-0.txt](https://github.com/user-attachments/files/17178268/limo_log.txt)


> This sounds like an issue with flatpak permissions. Where is this hard drive mounted?
Its mounted as on root as /Games

**Comment by limo-app** [comment]
> Its mounted as on root as /Games

By default Limo can only access files in the following locations: `~`, `/mnt`, `/media`, `/run/media`.
There are several different ways you can use to grant access to `/Games`, i recommend using [Flatseal](https://flathub.org/apps/com.github.tchx84.Flatseal).

> then attempting the syslink which crashes everything

Regardless of the permission issue, a crash should obviously never happen and i will try to fix this for the next update. Please report if this persists after adding read/ write permissions to `/Games`.

> although the app did not like the ~/

`~` not being interpreted as home is an issue i will fix with the next update.

**Comment by limo-app** [comment]
> (Could it be a requirement I've missed?)

Unlikely, Flatpaks have have most of their requirements built in. They only need a runtime to work, which is automatically installed when you install a Flatpak app.

From the output you sent, this is likely a bug in Limo.

**Comment by Nex-Crimen** [comment]
Update. This seems to have been a system issue, as after updating my system today, everything is working.

Saying that I terribly sorry for wasting your time trying to fix what appears to be a non-existent issue.

Hopefully the information here will help someone else at least.

**Comment by limo-app** [comment]
> This seems to have been a system issue, as after updating my system today, everything is working.

I've been away for a while, which is why it took so long to find and fix the issue. But this was a bug that has been fixed in 6eda51d14a8f096a9fb1e2545cd47a378c186ef7, which will be part of the next release. The crash occurred when switching to *Deploy for Current Deployer* and then clicking *Deploy* for any deployer other than the first in the list.

> Saying that I terribly sorry for wasting your time trying to fix what appears to be a non-existent issue.

No need to apologize. Even if this would have not been an issue with Limo, reporting a crash may still help others.
