### ISSUE TITLE
Limo Build Error: Fatal error: dll.hpp: No such file or directory

### ISSUE THREAD

**Issue by Heisenborgar** [limo-app/limo#43]
Hello, I'm trying to build Limo so I can do a PR regarding #42. But I encountered this issue when building on my Arch Linux setup. Here are the steps that I did:

1. Clone this repo.
2. Installed dependencies based on my distro: qt5, jsoncpp, libarchive, pugixml, openssl, cpr, libroot, catch2, doxygen.
3. Executed these commands:
mkdir tests/build - No error
cmake -DCMAKE_BUILD_TYPE=Release -S tests -B tests/build - No error
cmake --build tests/build - Errors:

[ 34%] Building CXX object CMakeFiles/tests.dir/home/patrick/Projects/Limo/limo/src/core/installer.cpp.o
/home/patrick/Projects/Limo/limo/src/core/installer.cpp:10:10: fatal error: dll.hpp: No such file or directory
   10 | #include <dll.hpp>
      |          ^~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/tests.dir/build.make:230: CMakeFiles/tests.dir/home/patrick/Projects/Limo/limo/src/core/installer.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/tests.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

Here's the whole process: [Pastebin](https://pastebin.com/EMyJex3V)

**Comment by limo-app** [comment]
As @OdinVex mentioned, the current CMAKE file is pretty bad. To be honest, this is my first project and i did not anticipate that people would add it to other package managers, which is why the non-flatpak part of the current file is mostly just tailored to my setup, which is obviously not ideal.

> Limo's got a lot of issues around assumption and polishing is also desperately needed

This is very likely due to my lack of experience. I hope this will all improve over time and would be grateful for advice, should something particularly bad stick out to you.

**Comment by limo-app** [comment]
> you use a lot of sfs namespacing even though QFile is included and is...right there

I realize this must seem really strange and using the Qt implementation would probably be better at this point. A bit of background: When i began writing Limo, i didn't know which GUI framework to use. To not entirely box myself into Qt from the beginning, i decided to strictly separate GUI classes from non-GUI classes by not using any Qt functionality when not absolutely necessary. This led to a situation where everything in src/core can be compiled without Qt, while the class *ApplicationManager* acts as a sort of interface to Qt code.
I am currently unsure if i should keep this separation.

> Plus the source format and variable naming such as var_name_ is...not need by me before

When starting out, i looked for a style guide to follow and found several references to the [Google one](https://google.github.io/styleguide/cppguide.html#Variable_Names). This is where some of the oddities, like the trailing underscore for class members, originate.
If this an odd choice, i would be happy to change my style to something more commonly used for C++. Do you have a suggestion?

> I found this most helpful for Qt projects:

Thank you! I will go over the warnings this produces.

**Comment by Heisenborgar** [comment]
Now fixed since I was now able to build successfully

**Comment by mattmcadoo** [comment]
For documentation's sake, I ran into this error that is in the issue title.  I run Gentoo and unrar is available in Portage, but the CMake configure portion needs to have it directly called out to use it via `cmake -DCMAKE_BUILD_TYPE=Release -DUSE_SYSTEM_LIBUNRAR=true -S . -B build` or at least it wasn't auto-detect for me.
