### ISSUE TITLE
[Error]: Could not find "libraryfolders.vdf"!

### ISSUE THREAD

**Issue by polluxau** [limo-app/limo#52]
Iv tried using limo a couple of times but i always get stuck at this point when trying to add my steam library so it can detect the games for modding, This is on flatpak

My games are mounted under /games and i have added flatpak to see that directory, i have libraryfolders.vdf in steamlibrary, the permission of that file is allowed to be modified by owner, group, others also

So im a bit confused :P
![image](https://github.com/user-attachments/assets/eda1d9a7-3cb1-4940-8263-74d5a42085a9)

Testing the aur version it works properly tho so its interesting, running flatpak through terminal doesnt output a error about this

**Comment by limo-app** [comment]
Flatpak applications run in a sandbox, which means they have very limited rights by default. Limo has read/ write access to the following locations: `~/` (except for `~/.var/app`), `/mnt`, `/media`, `/run/media` and `~/.var/app/com.valvesoftware.Steam` (the Flatpak Steam directory).
 In order for Flatpak Limo to access files in `/games`, you need to add permissions for that location. The easiest way to do this is probably by using a tool like [Flatseal](https://flathub.org/apps/com.github.tchx84.Flatseal).

**Comment by polluxau** [comment]
> Flatpak applications run in a sandbox, which means they have very limited rights by default. Limo has read/ write access to the following locations: `~/` (except for `~/.var/app`), `/mnt`, `/media`, `/run/media` and `~/.var/app/com.valvesoftware.Steam` (the Flatpak Steam directory).
>  In order for Flatpak Limo to access files in `/games`, you need to add permissions for that location. The easiest way to do this is probably by using a tool like [Flatseal](https://flathub.org/apps/com.github.tchx84.Flatseal).

Yes, as I said in that first post I have allowed Flatpak to see /games for limo in flatseal so that's why I'm confused :>

**Comment by limo-app** [comment]
> Yes, as I said in that first post

Sorry, i misread your message.
Is Steam installed as a Flatpak or natively on your system? You could check if this works if you enter the path manually.
For native steam the path should be `/home/user/.steam/steam/steamapps`.
For flatpak Steam: `/home/user/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps`.
One of these directories should contain the `libraryfolders.vdf` file.

**Comment by polluxau** [comment]
Im using system steam

Adding system steam directory through flatseal i get the error still

I have libraryfolders.vdf  in system steam also

![image](https://github.com/user-attachments/assets/ca6f99e4-1e24-443d-a115-196843690d50)

![image](https://github.com/user-attachments/assets/145bce96-e90a-44a1-aad1-69804450c841)

**Comment by limo-app** [comment]
Sorry for the confusion, i meant try to enter `/home/pollux/.steam/steam/steamapps` into the *Steam path* field in the import from Steam dialog field in Limo

**Comment by polluxau** [comment]
> Sorry for the confusion, i meant try to enter `/home/pollux/.steam/steam/steamapps` into the *Steam path* field in the import from Steam dialog field in Limo

Oh, yes that works! Thank you :)

**Comment by limo-app** [comment]
> Oh, yes that works! Thank you :)

Great :) This helped me identify the issue. A fix for other users will be part of the next update.
