### ISSUE TITLE
[Feature request] Allow use of system provided unrar instead of cloning one into folder during build process

### ISSUE THREAD

**Issue by sjp761** [limo-app/limo#53]
Would it be possible to use the system version of unrar instead of just cloning it during the build process? I think it will help simplify the build process slightly by reducing the needed steps

**Comment by limo-app** [comment]
I will look over the CMake file and update it for the non-flatpak build before the next release. This will most likely include adding an option for that case.

**Comment by Heisenborgar** [comment]
With the recent aa05b0157555d4fa2df7c9a38f2fc13e749edd68 commit. I now get build errors on AUR version of Limo. All is fine, until the final step of the building process. See:

==> Entering fakeroot environment...
==> Starting package()...
install: cannot stat 'build/Limo': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
error: failed to build 'limo-git-r60.f5e28e8-1': 
error: packages failed to build: limo-git-r60.f5e28e8-1

I also have errors with Doxygen, but I just ignore it. [Pastebin link here](https://pastebin.com/D8kLpQqy).

**Comment by limo-app** [comment]
> install: cannot stat 'build/Limo': No such file or directory

aa05b01 modified the CMake file with installation rules for Limo after compiling locally. Since it is common practice to use lower case names for executable names to start with a lower case letter, i renamed the output file from `Limo` to `limo`. This may cause the issue.

I will look into doxygen now.

**Comment by limo-app** [comment]
As for the original issue: aa05b01 also added a CMake option *USE_SYSTEM_LIBUNRAR*.

**Comment by limo-app** [comment]
> With the recent [aa05b01](https://github.com/limo-app/limo/commit/aa05b0157555d4fa2df7c9a38f2fc13e749edd68) commit. I now get build errors on AUR version of Limo. All is fine, until the final step of the building process. See:

I never used arch, but it looks like this should be fixed by replacing the line `install -Dm 755 -t "${pkgdir}/usr/bin" 'build/Limo'` should be `install -Dm 755 -t "${pkgdir}/usr/bin" 'build/limo'` in the `PKGBUILD` file.

**Comment by limo-app** [comment]
Sorry for the mess, i have fixed the executable name for AUR in [14713ec](https://github.com/limo-app/limo/commit/14713ec23087367557432c4f1f5cbc38cddd3ebc).

**Comment by Heisenborgar** [comment]
Hello @limo-app. Limo now builds just fine, it still errors for Doxygen but I tend to ignore it. However, launching Limo normally doesn't launch anymore. It says:

`Launching Limo Failed: Could not find program 'limo'`.

Launching it via terminal with `Limo` works fine tho
