### ISSUE TITLE
Some clarifications about the new tools section

### ISSUE THREAD

**Issue by Heisenborgar** [limo-app/limo#66]
Thanks for the new update, the new guided tool setup is a godsend and it works perfectly on first try with using Bethini. I need some clarifications though. 

1. Is it possible to see the generated files like from Pandora or Nemesis via the new tools section itself? Or do we have to rely on Reverse Deployer for this?
2. In the tools setup, the Working Directory is what I assume where the generated files would be sent over? 

With all that aside, I think with the new features such as the Reverse Deployer and Tools Setup, the Wiki now needs some updating.

Thanks!

**Comment by limo-app** [comment]
> 1. Is it possible to see the generated files like from Pandora or Nemesis via the new tools section itself? Or do we have to rely on Reverse Deployer for this

No. Currently there are no checks for files created by specific tools. The only way to determine if a file has been created by a tool would be to updated the reverse deployer files righter after running a tool. This could be done by binding a reverse deployer to a tool and having it auto update after every tool exit. Sounds useful, will think about adding this.

> 2\. In the tools setup, the Working Directory is what I assume where the generated files would be sent over

The working directory is where the tool is run. An example:
Let's say you have a file named `some_file` at `/tmp/some_file`. If you use `emacs` as tool executable and `/tmp` as working directory, you can use `some_file` as argument to get emacs to open  `/tmp/some_file`. 
In my experience, you should set the working directory to the directory containing the tool when you run through wine or protontricks. Some tools may want this to be the game's directory instead though.

> With all that aside, I think with the new features such as the Reverse Deployer and Tools Setup, the Wiki now needs some updating.

I agree. The new version is currently being built for the flatpak release. I will update the wiki once that is done.

**Comment by Heisenborgar** [comment]
Thank you!
