### ISSUE TITLE
Preserve title when reinstalling mod

### ISSUE THREAD

**Issue by poperigby** [limo-app/limo#76]
When I click `Reinstall From Local`, it will replace any custom name I've made for the mod, which is undesirable.

**Comment by limo-app** [comment]
I agree. Will fix this for the next update.

**Comment by poperigby** [comment]
@limo-app abb6ef8e88afbd6ba762419bc00f1b34b1ef20fa added this, right?

**Comment by limo-app** [comment]
> [abb6ef8](https://github.com/limo-app/limo/commit/abb6ef8e88afbd6ba762419bc00f1b34b1ef20fa) added this, right?

No, that commit auto fills the name in the *Add to group* / *Reinstall* field when downloading a new version of a mod with the same name. 
I forgot the add this change, sorry. It's now included in [efb426b](https://github.com/limo-app/limo/commit/efb426b1b3bcc7299827f522ffa037bb6f96fd56)

**Comment by poperigby** [comment]
No worries! Thanks!
