### ISSUE TITLE
[FYI] Symlinks troubleshooting - Does SKSE not work when using symlinks?

### ISSUE THREAD

**Issue by davozebi** [limo-app/limo#85]
I created the copy of the `skse64_loader.exe` and renamed it to `SkyrimSELauncher.exe` but when launching via Steam or Limo. I have the deployment method set as Sym Link for the Bin deployer. I wonder if this doesn't work because I'm using Flatpak Steam. IIRC symlinks don't work with exes and dlls right?

```
2024-12-17 16:55:19 [Info]: Running application 'Skyrim: Special Ed Edition' with command 'flatpak run com.valvesoftware.Steam -applaunch 489830'
2024-12-17 16:55:19 [Info]: Application 'Skyrim: Special Ed Edition' output: INFO:root:https://github.com/flathub/com.valvesoftware.Steam/wiki INFO:root:Will set XDG dirs prefix to /home/dz/.var/app/com.valvesoftware.Steam DEBUG:root:Checking input devices permissions WARNING:root:Missing permissions for input devices INFO:root:Overriding TZ to US/Eastern 
2024-12-17 16:55:19 [Info]: Application 'Skyrim: Special Ed Edition' exited with return code 0
```

I also tried using hard links but I'm not sure it works with a normal Flatpak Steam installation.

![image](https://github.com/user-attachments/assets/12750c27-0aad-464a-89e7-6d7ab378e251)

**Edit:** A workaround is to manually install SKSE like you would have to do with an MO2 setup.

**Comment by limo-app** [comment]
Unfortunately symlinks can create issues in some cases, since they don't behave exactly like the original file. I just tested this and i get the same behavior even with system Steam.

> I also tried using hard links but I'm not sure it works with a normal Flatpak Steam installation.

Due to the way Flatpak works, hard links cannot be created from Flatpak Limo to the Flatpak Steam directory.
There are two workarounds:
1. Create a new Steam library folder and install the games you wish to mod there. The reason hard links don't work is because the default library folder is in `~/.var/app`, which is restricted for Flatpak apps. Any other location should work, as long as it is on the same partition.
2.  Use copy deployment. While this is not ideal, SKSE is small so it would only require a few more MB of disk space.

**Comment by davozebi** [comment]
> Unfortunately symlinks can create issues in some cases, since they don't behave exactly like the original file. I just tested this and i get the same behavior even with system Steam.
> 
> > I also tried using hard links but I'm not sure it works with a normal Flatpak Steam installation.
> 
> Due to the way Flatpak works, hard links cannot be created from Flatpak Limo to the Flatpak Steam directory. There are two workarounds:
> 
>     1. Create a new Steam library folder and install the games you wish to mod there. The reason hard links don't work is because the default library folder is in `~/.var/app`, which is restricted for Flatpak apps. Any other location should work, as long as it is on the same partition.
> 
>     2. Use copy deployment. While this is not ideal, SKSE is small so it would only require a few more MB of disk space.

Is this also the case with regular mods? I installed SkyUI but the symlinks aren't adding it to the game.

**Comment by limo-app** [comment]
Other users have not reported issues with symlinks for mods like SkyUI. It may still create some issues, so it's probably safer to create a new library folder.

**Comment by davozebi** [comment]
I'm not sure it's possible to have multiple steam library folders on the same drive/partition and I didn't feel like trying to figure it out or move my current library folder. Instead I found another workaround: give Steam access to the staging directory via Flatseal. Now the symlinks work for both SKSE and SkyUI.

**Comment by limo-app** [comment]
> give Steam access to the staging directory via Flatseal.

Nice! I forgot that the access restriction would also apply in the other direction.
