### ISSUE TITLE
[FYI] NXM integration troubleshooting - Downloading/installing mods via nxm link isn't working after downloading one mod

### ISSUE THREAD

**Issue by davozebi** [limo-app/limo#86]
I'm not sure if this an issue from Nexus Mods or on my end.

**Comment by limo-app** [comment]
Could you try to start Limo with `--debug` as argument and check if the log shows any download requests after the first one?

For Flatpak, this command should work:
```
flatpak run io.github.limo_app.limo --debug
```

**Comment by davozebi** [comment]
No requests so it's probably not communicating with Limo right?

**Comment by limo-app** [comment]
Yes, this is likely because Limo is not set up to handle nxm links for some reason. The .desktop file has an entry that should take care of this. Are you using another mod manager that might be set as the default nxm handler instead?

**Comment by limo-app** [comment]
Strange. Does `xdg-mime query default x-scheme-handler/nxm` show Limo? You could try a different browser and see if that fixes it.

**Comment by davozebi** [comment]
Nope. It shows `modorganizer2-nxm-handler.desktop`.

**Comment by limo-app** [comment]
Try running
```
xdg-mime default io.github.limo_app.limo.desktop x-scheme-handler/nxm
```
Afterwards
```
xdg-mime query default x-scheme-handler/nxm
```
should output `io.github.limo_app.limo.desktop`. This should make Limo the default app for nxm links.

**Comment by davozebi** [comment]
From the first command I get:
`/sbin/xdg-mime: line 885: qtpaths: command not found`

**Comment by limo-app** [comment]
Nice! Not sure why the first command showed an error, maybe some Qt packages are missing.

> Is there a way to remove the other ones?

You may have some additional .desktop files in `/usr/share/applications` that handle nxm links. Deleting them or editing them to remove the association should remove them from the list. If you are running KDE the system settings provide a GUI for this in the *Default Applications* tab.

**Comment by davozebi** [comment]
Thanks I might fiddle with this if it annoys me. So far I've got the essentials set up with Community Shaders. Limo is really cool! Thank you!

**Comment by hazelnot** [comment]
Hm, I've been having the same issue, `xdg-mime default io.github.limo_app.limo.desktop x-scheme-handler/nxm` throws the same error, but `xdg-mime query default x-scheme-handler/nxm` just doesn't do anything for me, even with` xdg-mime query default x-scheme-handler/nxm`, even though it outputs `io.github.limo_app.limo.desktop`

**Comment by limo-app** [comment]
> Hm, I've been having the same issue, `xdg-mime default io.github.limo_app.limo.desktop x-scheme-handler/nxm` throws the same error, but `xdg-mime query default x-scheme-handler/nxm` just doesn't do anything for me, even with` xdg-mime query default x-scheme-handler/nxm`, even though it outputs `io.github.limo_app.limo.desktop`

Setting default applications is a pain sometimes and i unfortunately don't know why. 
This method will not work if you are using a browser installed through flatpak, but there is an alternative method if this is the case for you. Default apps for flatpaks seem to be stored in `~/.local/share/flatpak/db/desktop-used-apps`. This file contains a counter for how often you have opened a specific mime type with an application. If this counter reaches 3, the app will be your default for that type. The only way i have found to reliably change that is to open this file with a hex editor and change the counter back to 1.
