### ISSUE TITLE
Is there a way to delete mod files downloaded through mod manager download?

### ISSUE THREAD

**Issue by Saigaiii** [limo-app/limo#89]
I dont see it on the app section of limo so not sure if its somewhere else.

**Comment by Heisenborgar** [comment]
It's based on where you specified your Staging Directory when you first set it up, the folder should be named either .downloads or _downloads I forgor

**Comment by Saigaiii** [comment]
Oh yeah. I guess I meant a way to delete the downloads from within limo itself. Could be an enhancement/feature if its not there. Its not really a hassle, but it would be nice to have.

**Comment by limo-app** [comment]
I plan the add a *Downloads* tab for managing active/ completed downloads which will include this.

**Comment by Saigaiii** [comment]
Awesome. Thank you that would be huge QOL. As always the goat for mod manager on linux.
